services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: strive_frontend_speedrun-dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Helps HMR with Docker volumes
    volumes:
      # Mount source code into the container
      - ./web:/app:cached
      # Use a named volume for node_modules for performance/persistence
      - frontend_node_modules:/app/node_modules
    # Keep container running
    command: sleep infinity
    # User is set in devcontainer.json and handled by base image/Dockerfile
    # user: node

volumes:
  # Define the named volume
  frontend_node_modules:
